apiVersion: v1
kind: Service
metadata:
  name: my-service
#  namespace: my-namespace
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
 # namespace: my-namespace
  labels:
    app: my-app
spec:
  replicas: 2
  strategy:
        type: RollingUpdate
        rollingUpdate:
           maxSurge: 50%
           maxUnavailable: 50%
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: mobileapp
        image: ayush2107/nodde:1.0
        ports:
        - containerPort: 80
        env:
        - name: SERVER_PORT 
          value: "8090"
        volumeMounts:
        - mountPath: /var/www/html 
          name: demo-volume 

        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
        
      volumes:
      - name: demo-volume
        hostPath: 
          path: /tmp/data


---


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: my-ingress
#   #namespace: my-namespace
#   labels:
#     app: my-app
# spec: 
#   rules:
#     - http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend: 
#               service: 
#                 name: my-service
#                 port:
#                   number: 80
               

#---


apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
  #namespace: my-namespace
  labels:
    app: my-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
